# Generating Matrices

How to make matrices to work with.

In [3]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

Matrix of only zeros or ones:

In [5]:
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
Z1 = np.zeros((10,10))
Z1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
O = np.ones((10,10))
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

Matrix of random numbers:

In [8]:
R = np.random.random((10,10))
R

array([[ 0.78310893,  0.35784211,  0.33965653,  0.63229048,  0.51009725,
         0.17127184,  0.47730644,  0.099412  ,  0.2120756 ,  0.9440307 ],
       [ 0.49367788,  0.05124673,  0.35951961,  0.74967342,  0.97211912,
         0.33630506,  0.6346025 ,  0.0666722 ,  0.39022492,  0.29443576],
       [ 0.8589327 ,  0.41354941,  0.84677435,  0.47191734,  0.95851616,
         0.46889344,  0.07483157,  0.23441249,  0.49588943,  0.98607272],
       [ 0.37412228,  0.83098613,  0.02123215,  0.43387805,  0.03160792,
         0.44150007,  0.7126474 ,  0.63392914,  0.85267187,  0.7279375 ],
       [ 0.70057418,  0.74447152,  0.98210902,  0.36312975,  0.65372243,
         0.81330339,  0.46214738,  0.61381838,  0.01123039,  0.4684413 ],
       [ 0.50241527,  0.06792458,  0.84873132,  0.9926904 ,  0.17090649,
         0.9377343 ,  0.96070745,  0.33734815,  0.32211255,  0.89401701],
       [ 0.18091033,  0.0090857 ,  0.68405775,  0.20871806,  0.41465521,
         0.65663195,  0.05401698,  0.5132553 

Matrix of Random numbeers with Gaussian property, variance = 1 and mean = 0

In [13]:
G = np.random.randn(10,10)
G

array([[ -4.74986263e-01,   1.56771899e+00,  -8.64685618e-01,
          6.98414241e-01,  -7.65659087e-02,   2.39316245e-01,
          8.21810684e-02,   1.59670966e+00,   1.90270035e-01,
         -1.18714749e+00],
       [  1.10282830e+00,  -5.05467958e-01,   2.85091095e-01,
         -1.29459050e+00,  -1.37493383e-01,   1.50055764e+00,
         -1.56413969e+00,   2.13487355e+00,  -2.12988459e+00,
         -1.85130961e+00],
       [  8.89618810e-01,  -2.57961731e-01,   1.74942374e-02,
          6.41272609e-01,   1.16378520e+00,   4.06009616e-01,
         -8.73260454e-01,  -2.89041605e-01,  -5.97762088e-01,
         -6.03591918e-01],
       [  1.12752485e+00,  -1.15014546e+00,   3.28331043e-01,
         -2.23910127e+00,   2.10318162e-02,   1.78065326e-01,
         -5.79762115e-01,  -2.34693642e-01,   2.92018795e-01,
          2.79815751e+00],
       [  1.88871979e-01,   1.31058836e+00,  -1.74423058e+00,
          9.99150234e-01,  -6.08077782e-02,  -8.40794326e-01,
          1.15082008e+00

In [14]:
G.mean()

-0.021520758169209245

In [15]:
G.var()

0.99641244522185435