# More Matrix Operations

Matrix Inverse:

In [2]:
import numpy as np

A = np.array([[1,2],[3,4]])

Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Determinant of matrix:

In [6]:
np.linalg.det(A)

-2.0000000000000004

Diagonal of Matrix:

In [7]:
np.diag(A)

array([1, 4])

Make vector:

In [8]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

Outer and inner product:

In [9]:
a = np.array([1,2])
b = np.array([3,4])

np.inner(a,b)

11

In [10]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

Matrix Trace:

In [12]:
np.diag(A).sum()

5

Numpy gives a direct funcion:

In [13]:
np.trace(A)

5

Eigenvectors and eigenvalues:

In [15]:
X = np.random.rand(100,3)

voc = np.cov(X.T)
voc

array([[ 0.07270871,  0.00772217, -0.00301167],
       [ 0.00772217,  0.0840736 ,  0.00355129],
       [-0.00301167,  0.00355129,  0.06790438]])

In [17]:
np.linalg.eigh(voc)

(array([ 0.06396443,  0.0725737 ,  0.08814856]),
 array([[-0.56564723,  0.70321624, -0.43073209],
        [ 0.34915131, -0.26896956, -0.89763508],
        [-0.74708538, -0.65813547, -0.09338699]]))