In [15]:
import numpy as np


In [16]:
L = [1,2,3]
A = np.array([1,2,3])

In [17]:
for e in L:
    print (e)

for e in A:
    print (e)

1
2
3
1
2
3


In [18]:
L.append(4)

In [19]:
L = L + [5]

In [20]:
L2 = []

for e in L:
    L2.append(e+e)

In [21]:
L2

[2, 4, 6, 8, 10]

In [22]:
A + A

array([2, 4, 6])

In [23]:
2*A


array([2, 4, 6])

In [24]:
2*L


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [27]:
L2 = []


In [28]:
for e in L:
    L2.append(e*e)

In [29]:
L2

[1, 4, 9, 16, 25]

In [30]:
A**2

array([1, 4, 9])

In [31]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [32]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [33]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])